// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace boardwalk.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20201229210318_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("boardwalk.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cart_string")
                        .HasColumnType("TEXT");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("boardwalk.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A crisp, tasty apple",
                            ImageUrl = "apple.jpg",
                            Name = "Apple",
                            Price = 3.4500000000000002
                        },
                        new
                        {
                            Id = 2,
                            Description = "A banana",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Banana",
                            Price = 2.8500000000000001
                        },
                        new
                        {
                            Id = 3,
                            Description = "A super fast car",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Car",
                            Price = 345.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "A set of dice",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Dice",
                            Price = 5.6699999999999999
                        },
                        new
                        {
                            Id = 5,
                            Description = "Erase your mistakes with ease!",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Eraser",
                            Price = 0.67000000000000004
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fun for everyone",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Frisbee",
                            Price = 3.3300000000000001
                        },
                        new
                        {
                            Id = 7,
                            Description = "For all your seeing needs",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Glasses",
                            Price = 89.0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Goes with any outfit",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Hat",
                            Price = 34.289999999999999
                        },
                        new
                        {
                            Id = 9,
                            Description = "Satisfy your sweet tooth",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Ice Cream",
                            Price = 8.9499999999999993
                        },
                        new
                        {
                            Id = 10,
                            Description = "Wear them on your legs",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Jeans",
                            Price = 12.529999999999999
                        },
                        new
                        {
                            Id = 11,
                            Description = "Great for a windy day",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Kite",
                            Price = 12.529999999999999
                        },
                        new
                        {
                            Id = 12,
                            Description = "Brighten your day",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Light Bulb",
                            Price = 1.1200000000000001
                        },
                        new
                        {
                            Id = 13,
                            Description = "In case the ice cream wasn't enough",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Maple Syrup",
                            Price = 6.7300000000000004
                        },
                        new
                        {
                            Id = 14,
                            Description = "Jazz up your digits",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Nail Polish",
                            Price = 4.5499999999999998
                        },
                        new
                        {
                            Id = 15,
                            Description = "The fruit or the color?",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Orange",
                            Price = 1.8899999999999999
                        },
                        new
                        {
                            Id = 16,
                            Description = "Tickle the ivories",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Piano",
                            Price = 225.66
                        },
                        new
                        {
                            Id = 17,
                            Description = "Keep warm this winter",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Quilt",
                            Price = 17.34
                        },
                        new
                        {
                            Id = 18,
                            Description = "Protect your feet",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Running Shoes",
                            Price = 90.989999999999995
                        },
                        new
                        {
                            Id = 19,
                            Description = "Stay cool this summer",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Super Soaker",
                            Price = 24.989999999999998
                        },
                        new
                        {
                            Id = 20,
                            Description = "Drink it hot or cold",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Tea",
                            Price = 18.890000000000001
                        },
                        new
                        {
                            Id = 21,
                            Description = "Wear them under your jeans",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Underwear",
                            Price = 6.1200000000000001
                        },
                        new
                        {
                            Id = 22,
                            Description = "Make sure to practice",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Violin",
                            Price = 125.34
                        },
                        new
                        {
                            Id = 23,
                            Description = "Great for kids!",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Wagon",
                            Price = 67.540000000000006
                        },
                        new
                        {
                            Id = 24,
                            Description = "For beginners!",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Xylophone",
                            Price = 75.75
                        },
                        new
                        {
                            Id = 25,
                            Description = "Sewing, knitting, or weaving",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Yarn",
                            Price = 4.6699999999999999
                        },
                        new
                        {
                            Id = 26,
                            Description = "Really reaching for ideas here",
                            ImageUrl = "https://plchldr.co/i/300x200",
                            Name = "Zamboni??",
                            Price = 1001.1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
